task_webapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todoapp.urls')),
]

todoapp/urls.py
from django.urls import path
from .views import TasksListView,TaskCreateView,TaskDeleteView,TaskUpdateView,CustomLoginView,RegisterView,TaskDetailView
from django.contrib.auth.views import LogoutView

app_name = 'todoapp'

urlpatterns = [
    path('login/',CustomLoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(next_page='todoapp:login'),name='logout'),
    path('register/',RegisterView.as_view(),name='register'),

    path('', TasksListView.as_view(), name='list_task'),
    path('task/<int:pk>',TaskDetailView.as_view(),name='detail_task'),
    path('add/',TaskCreateView.as_view(),name='create_task'),
    path('delete/<int:pk>',TaskDeleteView.as_view(),name='delete_task'),
    path('update/<int:pk>',TaskUpdateView.as_view(),name='update_task'),
]

todoapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=False)
    
    def __str__(self):
        return self.title

    # class Meta:

todoapp/forms.py
from django import forms

class TaskForm(forms.Form):
    note = forms.CharField(label='Task :',widget=forms.Textarea())
    # note = forms.BooleanField(label='Task :',widget=forms.CheckboxInput())
    

todoapp/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from .models import Task
from django.views.generic import FormView,ListView,CreateView,DeleteView,UpdateView,DetailView

from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login

# Create your views here.

class RegisterView(FormView):
    template_name = 'todoapp/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('todoapp:list_task')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request,user)
            
        return super(RegisterView, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('list_task')
        return super(RegisterView, self).get(*args, **kwargs)

class CustomLoginView(LoginView):
    template_name = 'todoapp/login.html'
    fields = '__all__'
    redirect_authenticated_user = True
    def get_success_url(self):
        #don't forget this !
        return reverse_lazy('todoapp:list_task')
    

class TasksListView(LoginRequiredMixin,ListView):
     model = Task
     context_object_name = 'tasks'

     def get_context_data(self, **kwargs):
         context = super().get_context_data(**kwargs)
         context["tasks"] = context['tasks'].filter(user=self.request.user) 
         return context
     


class TaskDetailView(LoginRequiredMixin,DetailView):
    model = Task
    context_object_name = 'task'
    template_name = 'todoapp/task.html'


class TaskCreateView(LoginRequiredMixin,CreateView):
    model = Task
    fields  = ['title','description','created']
    success_url = reverse_lazy('todoapp:list_task')

    def form_valid(self, form):
        form.instance.user = self.request.user

        return super(TaskCreateView, self).form_valid(form)


class TaskDeleteView(LoginRequiredMixin,DeleteView):
    model = Task
    success_url = reverse_lazy('todoapp:list_task')
    
class TaskUpdateView(LoginRequiredMixin,UpdateView):
    model = Task
    fields = '__all__'
    success_url = reverse_lazy('todoapp:list_task')

todoapp/templates/todoapp/login.html
{% extends 'todoapp/main.html' %}

{% block content %}
<h3>Log in :</h3>

<div class="card w-50">
  <div class="card-body">
    <form method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <input class="btn btn-primary" type="submit" value="Login">
    </form>
    <p class='card-text'>Don't have an account? <a href="{% url 'todoapp:register' %}">Register</a></p>
  </div>
</div>
{% endblock content %}

todoapp/templates/todoapp/main.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <title>Task Web App</title>
  </head>
  <body>
    <div class="container">{% block content %}{% endblock content %}</div>
  </body>
</html>

todoapp/templates/todoapp/register.html
{% extends 'todoapp/main.html' %}

{% block content %}

<h3>Sign Up :</h3>

<div class="card w-50">
  <div class="card-body">
    <form method="POST">
      {% csrf_token %}
      <label>{{form.username.label}}</label>
        {{form.username}}
<br>
        <label>{{form.password1.label}}</label>
        {{form.password1}}
<br>
        <label>{{form.password2.label}}</label>
        {{form.password2}}
      <br>
      <input class="btn btn-primary" type="submit" value="Sign Up">
    </form>
    <p class='card-text'>Already have an account? <a href="{% url 'todoapp:login' %}">Login</a></p>
  </div>
</div>

{% endblock content %}

todoapp/templates/todoapp/task.html
<h1>Task:{{task}}</h1>

todoapp/templates/todoapp/task_confirm_delete.html
{% extends 'todoapp/task_list.html' %} {% block content %}
<div class="alert alert-danger" role="alert">
  <h1>ARE YOU SURE YOU WANT TO DELETE THIS TASK</h1>
</div>

<h6>{{note}}</h6>
<form method="POST">
  {% csrf_token %}
  <input class="btn btn-danger" type="submit" value="Delete" />
</form>
{% endblock content %}

todoapp/templates/todoapp/task_form.html
{% extends 'todoapp/task_list.html' %} {% block content %}
<div class="alert alert-success" role="alert">
  <h1>Create a New Task !</h1>
</div>
<form method="POST">
  {% csrf_token %} {{form.as_p}}
  <input class="btn btn-success" type="submit" value="Submit" />
</form>
{% endblock content %}

todoapp/templates/todoapp/task_list.html
{% extends 'todoapp/main.html' %}

{% block content %}
{% if request.user.is_authenticated %}
    <a href="{% url 'todoapp:logout' %}">Logout</a> 
{% else %}
    <a href="{% url 'todoapp:login' %}">Login</a> 
{% endif %}
<h1>Tasks List : </h1>

    <a href={% url 'todoapp:create_task' %}>ADD</a>
    <ul>
      {% for task in tasks %}

        <li>
          <a href="{% url 'todoapp:detail_task' task.id %}">{{task.title}}</a>
          <a href={% url 'todoapp:update_task' task.id %}>Update</a>
          <a href={% url 'todoapp:delete_task' task.id %}>Delete</a>
        </li>
      
      {% endfor %}
    </ul>

{% endblock content %}